mainPage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.main, name = 'news'),
	url(r'^news/(?P<n_id>[0-9]+)/$', views.show_news, name = 'show_news'),
	url(r'^about/', views.about, name = 'about'),

]

news_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainPage.urls', namespace = 'mainPage')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainPage/models.py
from django.db import models

SHORT_TEXT_LEN = 200

class News(models.Model):
	title = models.CharField(max_length=500, verbose_name = 'Заголовок')
	descriptions = models.TextField(verbose_name = 'Информация')
	date = models.DateTimeField(auto_now = True, verbose_name = 'Дата')

	def __str__(self):
		return self.title

	def get_short_text(self):
		if len(self.descriptions) > SHORT_TEXT_LEN:
			return self.descriptions[:SHORT_TEXT_LEN]
		else:
			return self.descriptions

	class Meta:
		verbose_name = 'Новости'
		verbose_name_plural = 'Новости'

mainPage/views.py
from django.shortcuts import render, get_object_or_404
from django.template.context_processors import csrf
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


from mainPage.models import News

def main(request):
	news = News.objects.all().order_by('-date')

	paginator = Paginator(news, 10)
	page = request.GET.get('page')

	try:
		news = paginator.page(page)
	except PageNotAnInteger:
		news = paginator.page(1)
	except EmptyPage:
		news = paginator.page(paginator.num_pages)

	args = {'news':news}

	return render(request, 'mainPage/base.html', args)


def show_news(request, n_id):
	args = {}
	args.update(csrf(request))
	args['news'] = get_object_or_404(News, id = n_id)
	return render(request, 'mainPage/news.html', args)

def about(request):
	return render(request, 'mainPage/about.html')

mainPage/templates/mainPage/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru-RU">
	<head>
		<meta charset="UTF-8">
		<title>Crypto Agent Bot: CAB - Crypto Agent Bot CAB Review: Cryptocurrency Trade Signals Group Telegram
		</title>
		<meta name="author" content>
		<meta name="description" content>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" type="images/x-icon" href="{% static 'img/Logo-little-spoon.png' %}">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	</head>
	<body>
		<header class="main-header">
			<div class="flex-container">
				<nav class="main-menu">
					<ul class="main-menu__list">
						<li class="main-menu__item"><a class="main-menu__link" href="/">news</a></li>
						<li class="main-menu__item"><a class="main-menu__link" href="{% url 'mainPage:about' %}">About Us</a></li>
					</ul>
				</nav>
				<nav class="locale-wrapper locale-news--wrapper">
					<ul class="locale__list">
						<li class="locale__item"><a class="locale__link" id="ru" title="Russian"><img class="locale__img" src="{% static 'img/locale/russian.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="en" title="English"><img class="locale__img" src="{% static  'img/locale/english.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="gb" title="German"><img class="locale__img" src="{% static 'img/locale/german.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="fr" title="French"><img class="locale__img" src="{% static 'img/locale/french.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="tur" title="Turkish"><img class="locale__img" src="{% static 'img/locale/turkish.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="po" title="Poland"><img class="locale__img" src="{% static 'img/locale/poland.png' %}"></a></li>
					</ul>
				</nav>
			</div>
		</header>
		<main class="maincontent">
			<div class="news--wrapper flex-container">
			{% for news in news %}
				<article class="news__card">
					<div class="news__descr--wrapper">
						<h3 class="news__heading">{{ news.title }}</h3>
						<span class="news__date">{{ news.date }}</span>
						<p class="news__descr">{{ news.get_short_text }}...</p>
						<a class="news__readmore" href="/news/{{ news.id }}">Readmore<span class="news__read">→</span></a>
					</div>
				</article>
			{% endfor %}
			</div>
		</main>
		<footer class="main-footer">
			<div class="flex-container">
				<p class="copyright">&copy2018 Crypto Agent Bot CAB Review : Cryptocurrency Trade Signals Group Telegram</p>
				<p class="powered-by">Powered by Django</p>
			</div>
		</footer>
		<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
		<script src="{% static 'locales/jquery.localize.min.js' %}"></script>
		<!-- script(src='https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.min.js')-->
		<script src="{% static 'js/main.js' %}"></script>
	</body>
  </html>

mainPage/templates/mainPage/footer.html
{% extends 'mainPage/base.html' %}
{% load staticfiles %}

{% block footer %}
    <footer class="main-footer">
        <div class="flex-container">
            <p class="copyright">&copy2018 Crypto Agent Bot CAB Review : Cryptocurrency Trade Signals Group Telegram</p>
            <p class="powered-by">Powered by Django</p>
        </div>
    </footer>
{% endblock %}

mainPage/templates/mainPage/header.html
{% extends 'mainPage/base.html' %}
{% load staticfiles %}

{% block  header %}
    <header class="main-header">
        <div class="flex-container">
            <nav class="main-menu">
                <ul class="main-menu__list">
                    <li class="main-menu__item"><a class="main-menu__link" href="/">news</a></li>
                    <li class="main-menu__item"><a class="main-menu__link" href="{% url 'mainPage:about' %}">About Us</a></li>
                </ul>
            </nav>
            <nav class="locale-wrapper">
                <ul class="locale__list">
                    <li class="locale__item"><a class="locale__link" id="ru" title="Russian"><img class="locale__img" src="{% static 'img/locale/russian.png' %}"></a></li>
                    <li class="locale__item"><a class="locale__link" id="en" title="English"><img class="locale__img" src="{% static  'img/locale/english.png' %}"></a></li>
                    <li class="locale__item"><a class="locale__link" id="gb" title="German"><img class="locale__img" src="{% static 'img/locale/german.png' %}"></a></li>
                    <li class="locale__item"><a class="locale__link" id="fr" title="French"><img class="locale__img" src="{% static 'img/locale/french.png' %}"></a></li>
                    <li class="locale__item"><a class="locale__link" id="tur" title="Turkish"><img class="locale__img" src="{% static 'img/locale/turkish.png' %}"></a></li>
                    <li class="locale__item"><a class="locale__link" id="po" title="Poland"><img class="locale__img" src="{% static 'img/locale/poland.png' %}"></a></li>
                </ul>
            </nav>
        </div>
    </header>
{% endblock %}

mainPage/templates/mainPage/news.html
{% load staticfiles %}

{% block  news %}
<!DOCTYPE html>
<html lang="ru-RU">
	<head>
		<meta charset="UTF-8">
		<title>Crypto Agent Bot: CAB - Crypto Agent Bot CAB Review: Cryptocurrency Trade Signals Group Telegram
		</title>
		<meta name="author" content>
		<meta name="description" content>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" type="images/x-icon" href="{% static 'img/Logo-little-spoon.png' %}">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	</head>
	<body>
		<header class="main-header">
			<div class="flex-container">
				<nav class="main-menu">
					<ul class="main-menu__list">
						<li class="main-menu__item"><a class="main-menu__link" href="/">news</a></li>
						<li class="main-menu__item"><a class="main-menu__link" href="{% url 'mainPage:about' %}">About Us</a></li>
					</ul>
				</nav>
				<nav class="locale-wrapper locale-news--wrapper">
					<ul class="locale__list">
						<li class="locale__item"><a class="locale__link" id="ru" title="Russian"><img class="locale__img" src="{% static 'img/locale/russian.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="en" title="English"><img class="locale__img" src="{% static  'img/locale/english.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="gb" title="German"><img class="locale__img" src="{% static 'img/locale/german.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="fr" title="French"><img class="locale__img" src="{% static 'img/locale/french.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="tur" title="Turkish"><img class="locale__img" src="{% static 'img/locale/turkish.png' %}"></a></li>
						<li class="locale__item"><a class="locale__link" id="po" title="Poland"><img class="locale__img" src="{% static 'img/locale/poland.png' %}"></a></li>
					</ul>
				</nav>
			</div>
		</header>
		<main class="maincontent">
			<div class="news__detail--wrapper flex-container">
				<h2 class"news__title">{{ news.title }}</h2>
				<span class="news__date">{{ news.date }}</span>
				<p class="news__descr">{{ news.descriptions }}</p>
			</div>
		</main>
		<footer class="main-footer">
			<div class="flex-container">
				<p class="copyright">&copy2018 Crypto Agent Bot CAB Review : Cryptocurrency Trade Signals Group Telegram</p>
				<p class="powered-by">Powered by Django</p>
			</div>
		</footer>
		<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
		<script src="{% static 'locales/jquery.localize.min.js' %}"></script>
		<!-- script(src='https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.min.js')-->
		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>
{% endblock %}

mainPage/templates/mainPage/news_list.html
{% extends 'mainPage/base.html' %}
{% load staticfiles %}

{% block  news %}
	<main class="maincontent">
		<div class="flex-container">
			<div class="news--wrapper">
				{% for news in news %}
					<article class="news__card">
						<div class="news__descr--wrapper">
						<h3 class="news__heading">{{ news.title }}</h3>
						<span class="news__date">{{ news.date }}</span>
						<p class="news__descr">{{ news.get_short_text }}...</p>
						<a class="news__readmore" href="/news/{{ news.id }}">Readmore<span class="news__read">→</span></a>
						</div>
					</article>
				{% endfor %}
			</div>
		</div>
	</main>
{% endblock %}